import {BANDS,CONFIG,getBand,antennaAllowed,initialBearing,greatCircleDistance,intermediatePoint} from './propagation.js';
import {RULES,formatTime,selectedTarget,inspectPath,bandScope,penaltyFor,missedTip} from './game.js';
/** One label for an attempt everywhere: the ten minutes it occupied, e.g. 00:00-00:10 UTC. */
export const attemptTime=minute=>`${formatTime(minute)}\u2013${formatTime(Math.min(1440,minute+RULES.attemptMinutes))} UTC`;
import {isListening} from './stations.js';
import {isLand} from './landmask.js';
import {ScoreCounter} from './reward.js';
export const $=id=>document.getElementById(id);
export const escapeHTML=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const distanceText=(km,units='km')=>`${Math.round(units==='mi'?km*.621371:km).toLocaleString('en-GB')} ${units}`;
export class UI {
  constructor(){this.settings={units:'km'};this.lastLogKey='';this.toastTimer=null;this.tutorialIndex=0;this.tutorial=[['READ THE DAY.','Start with SFI, K and the station windows. The map follows your simulated UTC clock, not your real local time. Ten stations are waiting somewhere on this Earth.'],['TUNE FOR THE PATH.','High bands like sunlight and high solar flux. Low bands often work better after dark. For a nearby station, try 40m and the low dipole. The grey line can help on the low bands.'],['CALL. LEARN. REPEAT.','Each call costs ten minutes. A failed call tells you what stopped the signal. Work each target once; CW, SSB and low power score more. You can wait, but cannot turn the clock back.']];}
  init(){if(!$('band-buttons'))return;this.score=new ScoreCounter($('score-display'));$('band-buttons').innerHTML=BANDS.map((b,i)=>`<button data-band="${b.id}" title="${b.mhz} MHz / shortcut ${i===9?'0':i===10?'-':i+1}" aria-pressed="false">${b.id}</button>`).join('');$('antenna-select').innerHTML=Object.entries(CONFIG.antennas).map(([id,a])=>`<option value="${id}">${a.name}</option>`).join('');}
  setSettings(s){this.settings=s;document.body.classList.toggle('reduced-motion',s.reducedMotion);$('quality-select').value=s.quality;$('units-select').value=s.units;$('sound-setting').checked=s.sound;$('motion-setting').checked=s.reducedMotion;document.querySelectorAll('[data-layer]').forEach(e=>{e.checked=Boolean(s.layers[e.dataset.layer]);e.disabled=s.quality==='low'&&e.dataset.layer!=='F2';});$('layer-toggle').setAttribute('aria-pressed',String(Boolean(s.layers.F2)));}
  route(screen){document.body.dataset.screen=screen;for(const element of document.querySelectorAll('.screen'))element.hidden=element.id!==`screen-${screen}`;window.scrollTo(0,0);const h=$(`screen-${screen}`)?.querySelector('h1[tabindex]');h?.focus({preventScroll:true});}
  briefing(state){const d=state.day;$('briefing-label').textContent=`${state.mode==='daily'?'DAILY #'+d.number:'PRACTICE'} / ${d.key} UTC`;$('briefing-heading').innerHTML=state.mode==='daily'?'DAILY BRIEFING<span class="acid">.</span>':'PRACTICE BRIEFING<span class="acid">.</span>';$('conditions').innerHTML=[['SFI',d.conditions.sfi,'Solar flux: higher values lift the F2 critical frequency.'],['K INDEX',d.conditions.kp,'Geomagnetic activity: high K weakens polar paths.'],['A INDEX',d.conditions.a,'A game-consistent indicator of daily magnetic activity.']].map(([label,value,copy])=>`<div class="condition"><span class="eyebrow">${label}</span><strong>${value}</strong><p>${copy}</p></div>`).join('');
    const c=d.conditions;$('weather-notes').innerHTML=(c.flare?`<strong>FLARE WATCH</strong> / ${formatTime(c.flare.start)}-${formatTime(c.flare.end)} UTC. Sunlit D-layer absorption rises fivefold.`:'<span class="acid">NO FLARE WATCH</span> / No scheduled absorption burst today.')+'<br>'+ (c.esPatches.length?`<strong>SPORADIC E</strong> / ${c.esPatches.length} northern-summer patch${c.esPatches.length===1?'':'es'}. ${c.esPatches.map(p=>`${p.lat}\u00b0N ${Math.abs(p.lon)}\u00b0${p.lon<0?'W':'E'}, ${p.radius} km radius, ${formatTime(p.start)}-${formatTime(p.end)}`).join('; ')} UTC.`:'SPORADIC E / No patches forecast.');
    if(state.startMinute>0)$('weather-notes').innerHTML+=`<br><span class="acid">ON AIR FROM ${formatTime(state.startMinute)} UTC</span> / Your day opens when the first station starts listening. Nothing is on air earlier.`;
    $('qth-name').textContent=`${d.qth.name}, ${d.qth.country}`;$('qth-grid').textContent=`${d.qth.locator} / ${d.qth.lat.toFixed(1)}, ${d.qth.lon.toFixed(1)} / fixed daily location`;
    $('briefing-targets').innerHTML=d.targets.map(t=>`<div class="brief-target"><strong>${t.callsign}</strong><span>${formatTime(t.start)}-${formatTime(t.end)}</span><span class="tiny">${escapeHTML(t.name)} / ${t.locator}</span><span class="tiny">RARITY ${t.rarity}/5</span></div>`).join('');
  }
  setupDay(state){const d=state.day;$('target-select').innerHTML=d.targets.map(t=>`<option value="${t.id}">${t.callsign}</option>`).join('');$('map-day').textContent=`${state.mode==='daily'?'DAILY #'+d.number:'PRACTICE'} / ${d.key}`;$('map-qth').textContent=d.qth.name.toUpperCase();$('map-weather').textContent=`${d.qth.locator} / SFI ${d.conditions.sfi} / K ${d.conditions.kp} / A ${d.conditions.a}`;this.lastLogKey='';this.briefing(state);}
  operating(state,busy=false){const t=selectedTarget(state),b=getBand(state.rig.band),worked=state.worked.includes(t.id),bearing=initialBearing(state.day.qth,t),units=this.settings.units;
    $('target-select').value=t.id;$('target-location').textContent=`${t.name}, ${t.country} / ${t.locator}`;
    $('qso-count').textContent=`${state.worked.length} / 10 QSOs`;
    $('target-data').innerHTML=`<div><strong>${distanceText(greatCircleDistance(state.day.qth,t),units)}</strong><span>SHORT PATH / ${bearing.toFixed(0)}\u00b0</span></div><div><strong>${formatTime(t.start)}-${formatTime(t.end)}</strong><span>UTC / ${worked?'WORKED':isListening(t,state.minute)?'LISTENING':'OFF AIR'}</span></div><div><strong>${t.rarity} / 5</strong><span>RARITY MULTIPLIER</span></div>`;
    $('target-bands').textContent=`ON AIR: ${t.bands.join(' / ')} | ${t.modes.join(' / ')}`;$('clock').textContent=formatTime(state.minute);$('time-slider').min=state.minute;$('time-slider').value=state.minute;$('time-slider').setAttribute('aria-valuetext',`${formatTime(state.minute)} UTC`);$('time-left').textContent=`${Math.floor((1440-state.minute)/60)}h ${(1440-state.minute)%60}m LEFT`;
    $('wait-window').disabled=state.minute>=t.start||busy;$('wait-window').classList.toggle('attention',!worked&&state.minute<t.start&&!busy);$('wait-window').textContent=state.minute>=t.end?'WINDOW CLOSED':state.minute>=t.start?'WINDOW OPEN':'WAIT FOR WINDOW';
    $('frequency').textContent=b.mhz.toFixed(3);$('rig-mode').textContent=state.rig.mode;$('rig-power').textContent=`${state.rig.power} W`;
    document.querySelectorAll('[data-band]').forEach(e=>{const valid=antennaAllowed(state.rig.antenna,e.dataset.band);e.disabled=!valid||busy;e.setAttribute('aria-pressed',String(e.dataset.band===state.rig.band));e.title=valid?`${getBand(e.dataset.band).mhz} MHz`:`${CONFIG.antennas[state.rig.antenna].name} cannot use ${e.dataset.band}. Change antenna first.`;});
    document.querySelectorAll('[data-mode]').forEach(e=>{e.disabled=busy||(state.rig.band==='30m'&&e.dataset.mode==='SSB');e.setAttribute('aria-pressed',String(e.dataset.mode===state.rig.mode));e.title=e.disabled&&!busy?'30m supports CW and FT8 only.':'';});document.querySelectorAll('[data-power]').forEach(e=>{e.setAttribute('aria-pressed',String(Number(e.dataset.power)===state.rig.power));e.disabled=busy;});
    const warning=state.rig.band==='30m'?'30m: CW / FT8 only. No SSB.':['yagi','loop'].includes(state.rig.antenna)?'Some bands are disabled for this antenna. Change antenna to access them.':'';$('rig-warning').hidden=!warning;$('rig-warning').textContent=warning;
    $('antenna-select').value=state.rig.antenna;for(const option of $('antenna-select').options){const valid=antennaAllowed(option.value,state.rig.band);option.disabled=!valid;option.textContent=CONFIG.antennas[option.value].name+(valid?'':` / unavailable on ${state.rig.band}`);}$('antenna-note').textContent=CONFIG.antennas[state.rig.antenna].description;
    $('bearing-control').hidden=state.rig.antenna!=='yagi';$('bearing-slider').value=state.rig.bearing;$('bearing-output').textContent=`${String(state.rig.bearing).padStart(3,'0')}\u00b0`;
    for(const id of ['target-select','antenna-select','bearing-slider','time-slider'])$(id).disabled=busy||state.finished;
    $('call-button').disabled=busy||worked||state.finished;$('call-callsign').textContent=busy?'TRANSMITTING...':worked?'ALREADY WORKED':t.callsign;
    $('radio-panel').setAttribute('aria-busy',String(busy));if(this.score)this.score.show(state.score);else $('score-display').textContent=`${state.score.toLocaleString('en-GB')} PTS`;
    $('target-rail').innerHTML=state.day.targets.map(target=>`<button data-target="${target.id}" aria-pressed="${target.id===t.id}" class="${state.worked.includes(target.id)?'worked':''}" title="${escapeHTML(target.name)} / ${formatTime(target.start)}-${formatTime(target.end)} UTC"><span>${target.callsign}</span><span class="target-status">${state.worked.includes(target.id)?'\u2713':isListening(target,state.minute)?'ON':'--'}</span></button>`).join('');
    this.renderHints(state);this.renderFeedback(state);this.renderLog(state);
  }
  renderFeedback(state){const entry=[...state.log].reverse().find(e=>e.targetId===state.selected),box=$('feedback');if(!entry){const t=selectedTarget(state);let head='READY WHEN YOU ARE',copy='Check the listening window, choose your setup, then call.',warn=false;
      if(state.minute<t.start){warn=true;head=`${t.callsign} IS OFF AIR UNTIL ${formatTime(t.start)} UTC`;copy=`Press WAIT FOR WINDOW to jump the clock to ${formatTime(t.start)} (no cost), or pick a station marked ON. Calling now costs 10 minutes and cannot succeed.`;}
      else if(state.minute>=t.end){warn=true;head=`${t.callsign} HAS GONE OFF AIR`;copy=`Its window was ${formatTime(t.start)}-${formatTime(t.end)} UTC. Pick another station.`;}
      else if(!t.bands.includes(state.rig.band)){warn=true;head=`${t.callsign} IS NOT ON ${state.rig.band.toUpperCase()}`;copy=`Listening on ${t.bands.join(', ')}. Change band before you call.`;}
      else if(!t.modes.includes(state.rig.mode)){warn=true;head=`${t.callsign} IS NOT USING ${state.rig.mode}`;copy=`Listening in ${t.modes.join(' / ')}. Change mode before you call.`;}
      box.className=`feedback${warn?' notice':''}`;box.innerHTML=`<span class="eyebrow">${warn?'! ':''}${escapeHTML(head)}</span><p>${escapeHTML(copy)}</p>`;$('hop-details').hidden=true;return;}
    const r=entry.result;box.className=`feedback ${r.ok?'good':'bad'} ${r.qsb?'marginal':''}`;box.innerHTML=`<span class="eyebrow">${r.ok?'\u2713 QSO LOGGED':'\u00d7 '+escapeHTML(r.reason.toUpperCase())}${r.qsb?' / QSB':''} / ${attemptTime(entry.minute)}</span><p>${escapeHTML(r.detail)}</p>${entry.points?`<p class="acid">+${entry.points.toLocaleString('en-GB')} POINTS</p>`:''}`;
    $('hop-details').hidden=!r.hops.length;
    $('hop-table').innerHTML='<table><thead><tr><th>HOP</th><th>MUF MHz</th><th>D LOSS dB</th><th>REFL. dB</th></tr></thead><tbody>'+r.hops.map((h,i)=>`<tr class="${h.failed?'failed':''}"><td>${h.failed?'\u00d7 ':''}${i+1}</td><td>${h.mufMHz?.toFixed(1)??'GROUND'}</td><td>${h.absDb.toFixed(1)}</td><td>${h.reflection.toFixed(1)}</td></tr>`).join('')+'</tbody></table>'+`<p class="tiny">${r.mechanism} / ${r.angle.toFixed(1)}\u00b0 take-off / Polar loss ${r.polarLossDb.toFixed(1)} dB${Number.isFinite(r.snr)?' / SNR '+r.snr.toFixed(1)+' dB':''}</p>`;
  }
  renderLog(state){const key=`${state.day.seed}:${state.log.length}`;if(key===this.lastLogKey)return;this.lastLogKey=key;$('log-count').textContent=`${state.log.length} ATTEMPTS`;$('log-list').innerHTML=state.log.slice().reverse().map(e=>`<div class="log-entry ${e.result.ok?'good':'bad'}"><div class="section-top"><strong>${e.result.ok?'\u2713':'\u00d7'} ${e.callsign}</strong><span>${attemptTime(e.minute)}</span></div><p>${e.rig.band} / ${e.rig.mode} / ${e.rig.power} W / ${e.result.ok?'+'+e.points+' pts':escapeHTML(e.result.reason)}${e.result.qsb?' / QSB':''}</p></div>`).join('')||'<p class="tiny">No transmissions yet.</p>';}
  renderHints(state){const hints=state.hints[state.selected]||[],worked=state.worked.includes(state.selected);document.querySelectorAll('[data-hint]').forEach(e=>{const used=hints.includes(e.dataset.hint);e.classList.toggle('purchased',used);e.disabled=worked;e.setAttribute('aria-pressed',String(used));});const out=$('hint-output');out.hidden=!hints.length;if(!hints.length)return;const r=inspectPath(state);let html=`<p class="tiny">THIS TARGET: ${Math.round(penaltyFor(state,state.selected)*100)}% POINTS PENALTY</p>`;if(hints.includes('muf'))html+=`<p>PATH MUF <span class="acid">${r.mufMHz?.toFixed(1)??'GROUND WAVE'}${r.mufMHz?' MHz':''}</span></p>`;if(hints.includes('absorption'))html+=`<p>D-LAYER LOSS <span class="acid">${r.absDb.toFixed(1)} dB</span></p>`;if(hints.includes('scope')){const scope=bandScope(state);html+='<div class="scope-bars" role="img" aria-label="Rough path MUF over the next six hours">'+scope.map(p=>`<div class="scope-bar"><span>${p.mufMHz?Math.round(p.mufMHz):0}</span><i style="height:${Math.max(2,Math.min(60,(p.mufMHz||0)*1.5))}px"></i><span>${formatTime(p.minute)}</span></div>`).join('')+'</div><p class="tiny">Rounded MHz / current path. MUF alone does not guarantee a decode.</p>';}out.innerHTML=html;}
  results(state,stats){$('results-label').textContent=`${state.mode==='daily'?'DAILY #'+state.day.number:'PRACTICE'} / ${state.day.key} UTC`;$('results-score').textContent=state.score.toLocaleString('en-GB');$('results-qsos').textContent=`${state.worked.length} / 10`;$('results-grid').innerHTML=state.day.targets.map(t=>{const win=state.log.find(e=>e.targetId===t.id&&e.result.ok);return `<div class="result-cell ${win?(win.result.qsb?'marginal':'good'):'bad'}">${win?'\u2713':'\u00d7'} ${t.callsign}<span>${win?win.result.qsb?'QSB / +'+win.points:'+'+win.points+' PTS':'NOT WORKED'}</span></div>`;}).join('');const best=state.log.filter(e=>e.result.ok).sort((a,b)=>b.result.distanceKm-a.result.distanceKm)[0];$('best-dx').textContent=best?`BEST DX / ${best.callsign} / ${distanceText(best.result.distanceKm,this.settings.units)} / ${best.rig.band} ${best.rig.mode}`:'NO QSOs THIS ROUND / Every failed call is a clue.';$('results-tip').textContent=missedTip(state);$('stats-line').textContent=state.mode==='daily'?`LOCAL BEST ${(stats.best||0).toLocaleString('en-GB')} PTS / STREAK ${stats.streak||0} / BEST STREAK ${stats.bestStreak||0}`:'PRACTICE ROUND / Does not affect daily scores or streaks.';$('next-practice').hidden=state.mode!=='practice';$('tomorrow').hidden=state.mode!=='daily';this.drawResultsMap(state);}
  drawResultsMap(state){const c=$('results-map'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.fillStyle='#09110c';ctx.fillRect(0,0,w,h);ctx.fillStyle='#1c2a20';for(let lat=-89;lat<90;lat+=2)for(let lon=-179;lon<180;lon+=2)if(isLand(lat,lon))ctx.fillRect((lon+179)/360*w,(89-lat)/180*h,w/180+1,h/90+1);const xy=p=>({x:(p.lon+180)/360*w,y:(90-p.lat)/180*h});for(const target of state.day.targets){const win=state.log.find(e=>e.targetId===target.id&&e.result.ok);ctx.strokeStyle=win?win.result.qsb?'#ffbf69':'#d6ff00':'#ff8585';ctx.globalAlpha=win?.95:.5;ctx.lineWidth=win?1.6:1;ctx.beginPath();let previous=null;for(let i=0;i<=90;i++){const p=xy(intermediatePoint(state.day.qth,target,i/90));if(!previous||Math.abs(p.x-previous.x)>w/2)ctx.moveTo(p.x,p.y);else ctx.lineTo(p.x,p.y);previous=p;}ctx.stroke();const p=xy(target);ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.arc(p.x,p.y,3,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;const home=xy(state.day.qth);ctx.fillStyle='#ecefe7';ctx.fillRect(home.x-4,home.y-4,8,8);}
  tutorialStep(index){this.tutorialIndex=index;const [title,copy]=this.tutorial[index];$('tutorial-step').textContent=`0${index+1} / 03`;$('tutorial-symbol').textContent=`0${index+1}`;$('tutorial-heading').textContent=title;$('tutorial-copy').textContent=copy;$('tutorial-next').textContent=index===2?'READY TO OPERATE':'NEXT \u2192';}
  toast(message){clearTimeout(this.toastTimer);$('toast').textContent=message;$('toast').hidden=false;this.toastTimer=setTimeout(()=>{$('toast').hidden=true;},4600);}
  pause(){clearTimeout(this.toastTimer);if($('toast'))$('toast').hidden=true;}
}
